### ISSUE TITLE
No visual indication that user can select second topic

### ISSUE THREAD

**Issue by Aoterra** [working-title/whats-next#7]
When the user picks a subject area on the front page (eg Technology), user is presented with a list of career categories. When hovering over a subject area, the user cursor changes to the pointing hand. There is no visual indicator for the career categories. Please fix this.

**Comment by lena-pl** [comment]
I just fixed this (to an extent) – now the cursor changes in both scenarios. I generally think the visual feedback on that part of the page should be better though. Maybe highlighting the subject choice instead of underlining it would be more appropriate? I'm finding the underlining a little messy and confusing. 

What does everyone else think?

**Comment by shadrx** [comment]
I think this is no longer an issue we need to fix with the move to the new layout. Closed!
